def pattern(winner):
    print("                                    ",end=" ")
    print("        |        |        ")
    print("                                    ",end=" ")
    print("    ",winner[1]," |   ",winner[2],"  |    ",winner[3],"   ")
    print("                                    ",end=" ")
    print("        |        |        ")
    print("                                    ",end=" ")
    print(" ___________________________")
    print("                                    ",end=" ")
    print("        |        |        ")
    print("                                    ",end=" ")
    print("    ",winner[4]," |   ",winner[5],"  |    ",winner[6],"    ")
    print("                                    ",end=" ")
    print("        |        |        ")
    print("                                    ",end=" ")
    print(" ___________________________")
    print("                                    ",end=" ")
    print("        |        |        ")
    print("                                    ",end=" ")
    print("    ",winner[7]," |   ",winner[8],"  |    ",winner[9],"   ")
    print("                                    ",end=" ")
    print("        |        |        ")
